[package]
name = "atcoder-submissions-to-csv"
version = "0.1.0"
authors = ["ichyo <ichyo00@gmail.com>"]

[dependencies]
chrono = "0.4"
csv = "1.0.0-beta"
scraper = "0.4"
regex = "0.2"
reqwest = "0.8"
